version: '3.8'

services:
  allocation:
    container_name: test_allocation
    build: ./test_allocation
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./test_allocation:/app
    ports:
      - 8000:8000

  allocation_db:
    container_name: allocation_db
    image: postgres:14.1-alpine
    volumes:
      - pg_data_allocation:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=allocation_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  # warehouse_db:
  #   container_name: warehouse_db
  #   image: postgres:14.2
  #   environment:
  #     - POSTGRES_DB=warehouse_db
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=admin
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data/


  # localstack:
  #   container_name: localstack
  #   image: localstack/localstack:0.14.2
  #   network_mode: bridge
  #   privileged: true
  #   ports:
  #     - '4566:4566'
  #   environment:
  #     - SERVICES=${SERVICES- }
  #     - DATA_DIR=/tmp/localstack
  #     - LAMBDA_EXECUTOR=docker-reuse
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #     - AWS_EXECUTION_ENV=true
  #   volumes:
  #     - ".volume/tmp/localstack:/tmp/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"


volumes:
  pg_data_allocation: