version: '3.7'

services:
  warehouse:
    container_name: warehouse
    build: ./warehouse
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./warehouse/:/app
    ports:
      - 8002:8000

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=micro_warehouse
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata: