version: '3.8'

services:
  # payments:
  #   container_name: payments
  #   build: ./payments
  #   command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
  #   volumes:
  #     - ./payments/:/app
  #   ports:
  #     - 8001:8000

  warehouse:
    container_name: warehouse
    build: ./warehouse
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./warehouse/:/app
    ports:
      - 8002:8000

  db:
    container_name: db
    image: postgres:14.2
    environment:
      - POSTGRES_DB=micro_warehouse
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - pgdata:/var/lib/postgresql/data/

  localstack:
    container_name: localstack
    image: localstack/localstack:0.14.2
    network_mode: bridge
    privileged: true
    ports:
      - '4566:4566'
    environment:
      - SERVICES=${SERVICES- }
      - DATA_DIR=/tmp/localstack
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_EXECUTION_ENV=true
    volumes:
      - ".volume/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  pgdata: